spring:
  application:
    name: ticket-service

  data:
    mongodb:
      host: mongodb
      port: 27017
      database: ticketSystem

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 9093

# Eureka Setup
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:9090/eureka/
  instance:
    prefer-ip-address: true
